### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by zhoudreames** [AntonBankevich/jumboDB#2]
i got those result when i using jumboDB software with hifi data,i dont know which is my finally assemly sequence,could you help me ,thanks~
![image](https://user-images.githubusercontent.com/54714639/107511672-c1035700-6be0-11eb-9912-23009c9ed037.png)

**Comment by AntonBankevich** [comment]
Thank you for you interest in jumboDB. The edge sequences are in graph.fasta file. You can see more details on it in "Output of de Bruijn graph construction" section of the manual.
Also since you are looking for the "final assembly sequence" it is possible that there is a confusion about what jumboDB actually does. JumboDB is a tool for fast and memory efficient de Bruijn graph construction for large k (see readme). It is not a full genome assembly pipeline. Genome assembler LJA that is based on jumboDB (and also contains error correction and repeat resolution modules) is in development and we plan to release it within 2 months.
